clear;clc;
expression = '<(?<attribute>\w+)>(?<value>.*?)</\k<attribute>>';
str = ['<Remitente>',...
               '<Nombre>Nombre del remitente</Nombre>',...
               '<Mail> Correo del remitente </Mail>',...
          '</Remitente>'];
regexp(str,expression,'names');